version: 1.3.0-{branch}-{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - dev
image: Visual Studio 2017 
init:
  - dotnet --version
build_script:
- ps: .\build\build.ps1
test_script:
- ps: .\build\test.ps1
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: 3UPsnu7EsXsz0r5sDBm0k5AQwzd6LVpdLSMTZgB/5Cm2QLNW7+m2KCqRNnNAfA9t
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only